"""extend requests table

Revision ID: bfb9c88b52b4
Revises: 4e85c98c55f1
Create Date: 2026-08-10 13:50:52.896925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfb9c88b52b4'
down_revision: Union[str, Sequence[str], None] = '4e85c98c55f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('title', sa.String(length=200), nullable=False))
    op.add_column('requests', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('requests', sa.Column('applicant_name', sa.String(length=100), nullable=False))
    op.add_column('requests', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'updated_at')
    op.drop_column('requests', 'applicant_name')
    op.drop_column('requests', 'description')
    op.drop_column('requests', 'title')
    # ### end Alembic commands ###
